### PR TITLE
Fix miscellaneous bugs

### LINKED ISSUE #50: 1.21 seems to require an install on both client and server
I get kicked from my server with the following error:
```
[23:03:21] [Render thread/ERROR]: Received unknown remote registry entries from server
[23:03:21] [Render thread/ERROR]: Registry entry (tinkerers_smithing:repair) is missing from local registry (minecraft:recipe_serializer)
[23:03:21] [Render thread/ERROR]: Registry entry (tinkerers_smithing:sacrifice) is missing from local registry (minecraft:recipe_serializer)
[23:03:21] [Render thread/ERROR]: Registry entry (tinkerers_smithing:smithing) is missing from local registry (minecraft:recipe_serializer)
[23:03:21] [Render thread/ERROR]: Registry entry (tinkerers_smithing:shapeless) is missing from local registry (minecraft:recipe_serializer)
[23:03:21] [Render thread/ERROR]: Registry remapping failed!
java.util.concurrent.CompletionException: net.fabricmc.fabric.impl.registry.sync.RemapException: Received 4 registry entries that are unknown to this client.
```
Seems like something that's been fixed before? Found a similar looking closed issue.

Edit: Opened a PR to fix

### PR DESCRIPTION
**Pull request by PROMETHIA-27**
Fixes #50, #46

Fixes:
- Deworking not working
  - A mixin had the wrong ordinal (probably caused by method implementation changing)
- Keepers instantly breaking
  - A mixin was causing this, see below
- Clients without TS not being able to connect to servers with it
  - As of 1.21 it seems like registries are synced more aggressively and a mixin is needed to stop the sync manager from syncing specific registrations (Source: https://github.com/ViaVersion/ViaFabricPlus/commit/8c34100ee15976b77cba05093ec6aa841e74ad24#diff-1bb81968b68c9dfdf16552315d9fce3ae287b74ab1441349019a5052ac4dfe2bR31)

For fixing keepers instabreaking:
```java
private int dontBreakResetKeepers(int damage) {
    return isKeeper() ? ((ItemStack) (Object) this).getMaxDamage() : damage;
}
```
Commenting this out and just returning `damage` fixes it. I can't tell why this is here? It seems like its sole purpose would be to break keepers instantly.

### CODE REVIEW

**Comment by sisby-folk** [comment]
The point of that mixin is to prevent durability from becoming negative as a kept tool is used (so it stays at 0) - it should only be triggering when the durability is *at* 0, which seems to be the issue.

Can you peek your fix in game and ensure that keepers aren't getting negative durability when used while broken?

**Comment by PROMETHIA-27** [comment]
Oh that makes sense! It doesn't seem like anything goes negative? Tested sword, pickaxe, elytra, shears, flint, fishing rod. At least as long as the advanced tooltips are telling the truth. However I did notice that shears don't actually stop working, so I'll throw in a fix for that too.

File: src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+import org.spongepowered.asm.mixin.injection.Redirect;
+
+import java.util.Objects;
+
+@Mixin(RegistrySyncManager.class)
+public abstract class MixinRegistrySyncManager {
+	@Redirect(method = "createAndPopulateRegistryMap", at = @At(value = "INVOKE", target = "Lnet/minecraft/registry/Registry;getId(Ljava/lang/Object;)Lnet/minecraft/util/Identifier;"))
+	private static @Nullable <T> Identifier skipRecipes(Registry<T> instance, T t) {
+		final Identifier id = instance.getId(t);
+		if (
```
Comment (sleepingdragoninn) [inline src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java]: correct me if I'm wrong, can you just use an instanceof ServerRecipe on t here?

File: src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+import org.jetbrains.annotations.Nullable;
+import org.spongepowered.asm.mixin.Mixin;
+import org.spongepowered.asm.mixin.injection.At;
+import org.spongepowered.asm.mixin.injection.Redirect;
+
+import java.util.Objects;
+
+@Mixin(RegistrySyncManager.class)
+public abstract class MixinRegistrySyncManager {
+	@Redirect(method = "createAndPopulateRegistryMap", at = @At(value = "INVOKE", target = "Lnet/minecraft/registry/Registry;getId(Ljava/lang/Object;)Lnet/minecraft/util/Identifier;"))
```
Comment (sleepingdragoninn) [inline src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java]: can this be achieved without a redirect? possibly using a different target or a mixinextras annotation?

File: src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+import net.minecraft.util.Identifier;
+import org.jetbrains.annotations.Nullable;
+import org.spongepowered.asm.mixin.Mixin;
+import org.spongepowered.asm.mixin.injection.At;
+import org.spongepowered.asm.mixin.injection.Redirect;
+
+import java.util.Objects;
+
+@Mixin(RegistrySyncManager.class)
+public abstract class MixinRegistrySyncManager {
```
Comment (sleepingdragoninn) [inline src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java:12]: TSmithing on other versions has reasonable EMI support both with and without TSmithing itself on the client - can you check if this preserves that?

File: src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java (hunk 1 above)
Comment (PROMETHIA-27) [reply src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java]: No, that doesn't seem to work, though I'm not sure why. 
Specifically this is what I tried, in case it was just wrong:
```java
if (t instanceof ServerRecipe<?>) { return null; }
return instance.getId(t);
```

Comment (PROMETHIA-27) [reply src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java]: Oh, because the serverrecipe serializer is registered, not the recipe itself. I'll try that

File: src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java (hunk 3 above)
Comment (PROMETHIA-27) [reply src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java:12]: I was able to write a new version of the mixin: 
```java
@ModifyVariable(method = "createAndPopulateRegistryMap", at = @At("STORE"), ordinal = 1, remap = false)
private static Identifier skipRecipes(Identifier id, @Local(ordinal = 0) Object obj) {
	if (ServerRecipe.class.isAssignableFrom(obj.getClass().getEnclosingClass())) {
		return null;
	}
	return id;
}
```
Which I think is quite clean, and works, however it also completely breaks EMI compat, somehow an unexplained internal NullPointerException gets thrown *somewhere* with this version of the mixin. The original mixin works fine.

Comment (PROMETHIA-27) [reply src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java:12]: I was being silly, just had to check for nulls in the mixin itself.

File: src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java (hunk 2 above)
Comment (PROMETHIA-27) [reply src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java]: Figured out what I think is a cleaner method

File: src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java (hunk 3 above)
Comment (PROMETHIA-27) [reply src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java:12]: Noticeable issues (with TSmithing only serverside, EMI only clientside because serverside EMI seems broken regardless of TSmithing):
- EMI thinks netherite is repaired with netherite (it cannot be, and without TSmithing on client the anvil will *very* briefly think it can)
- EMI doesn't suggest that netherite scrap can be used to dework
Other than that things seem to be working fine?

With TSmithing clientside as well, these issues are gone.

**Comment by PROMETHIA-27** [comment]
Added mixins to disable using broken shears on: mooshrooms, bogged, wolves, pumpkins, snow golems, and beehives/nests

File: src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java (hunk 3 above)
Comment (sleepingdragoninn) [reply src/main/java/folk/sisby/tinkerers_smithing/mixin/MixinRegistrySyncManager.java:12]: pretty sure that's the expected level of parity! great work ^^

**Comment by sisby-folk** [comment]
Hmm, shears ends up with a *lot* of special casing. Maybe it could be handled at the interact mob packet level?

Also, shouldn't the interact block mixin on item stack handle bee nests?

**Comment by PROMETHIA-27** [comment]
> Maybe it could be handled at the interact mob packet level?

I'm not sure how exactly to go about that at the minute, but i could poke around and see if I can find something.
> Also, shouldn't the interact block mixin on item stack handle bee nests?

Apparently not; i did test it first before implementing. Much like the other blocks and entities, the logic is "when I'm interacted with -> check if the interactor was holding shears and then continue from there" rather than shears themselves driving the logic.

**Comment by sisby-folk** [comment]
How does that work with pathing with shovels and clearing bark with axes then? I was pretty sure we covered those cases, so this might be a 1.21 regression?

**Comment by PROMETHIA-27** [comment]
Axes and shovels are fine, they work when they should and don't when they're broken

**Comment by PROMETHIA-27** [comment]
Figured out how to replace all the special cases by ignoring incoming packets when the player uses a broken keeper. Haven't tested as much though, working on another mod atm.

**Comment by sisby-folk** [comment]
That's all good! I'm assuming this will create a funny little special case where you can't open chests / crafting tables / etc while holding a broken tool, but I think that's okay

**Comment by PROMETHIA-27** [comment]
That appears to be the case!

**Review by sleepingdragoninn — APPROVED** [review]
Thanks again for this, I'll merge this now but I might not be able to get a good looking release out until I'm back in two weeks - I'll see if I can throw the gh actions jar onto modrinth
